version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: cra:dev
    container_name: cra
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api:dev
    container_name: api
    volumes:
      - ./api/src:/api/src
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DB_URL=mongodb://127.0.0.1:27017
      - DB_NAME=root
    depends_on:
      - db
  db:
    volumes:
      - ./api/src/db/connection.ts:/api/src/db/connection.ts
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - 27017:27017