version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: cra:dev
    container_name: cra
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api:dev
    container_name: api
    volumes:
      - ./api/src:/api/src
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DB_URL=
      - DB_NAME=root